### ISSUE TITLE
Link from browser opens always within the same browser

### ISSUE THREAD

**Issue by arno-jost** [nref/BrowseRouter#24]
clicking on a link in (i.e.) Firefox will always open it in a new Tab/Window  in Firefox independent if the URL matches any entry from the config.ini

This is probably by design and I just don't understand the subject enough. Sorry if that's the case ;-)

**Comment by nref** [comment]
Hey there, and thanks for opening this issue.

The current behavior is on purpose, but I wouldn't say it is by design so much as by limitation of how browsers work.

When you click on a link in a browser, it will always open it in that browser. It doesn't ask the OS what to do with it, so BrowserRouter doesn't even run. 

For custom URI schemes e.g. `myapp://some/deeplink`, the OS launches the app registered for `myapp://`. BrowseRouter also doesn't run in this case.

As a flow chart:

```
[Click a link outside of a browser] -> [BrowserRouter] -> [configured browser opens the link]

[Click a link in browser X] -> [browser X opens the link]

[Click msteams://some/deeplink] -> [Microsoft Teams opens the link]
```
